version: '3.8'

services:
  app:
    build: .
    container_name: interview-app
    ports:
      - "3000:3000"    # Avoid port 8080, Nest default is 3000
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_USERNAME: root
      DB_PASSWORD: example
      DB_DATABASE: interview
    networks:
      - interview-net

  db:
    image: mysql:8.0
    container_name: interview-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: interview
      MYSQL_USER: interview
      MYSQL_PASSWORD: interview123
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - interview-net
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s

  adminer:
    image: adminer:4.8.1-standalone  # use stable standalone build to avoid PHP segfault
    container_name: interview-adminer
    restart: always
    depends_on:
      db:
        condition: service_healthy
    environment:
      # default MySQL server for Adminer UI
      ADMINER_DEFAULT_SERVER: db
    ports:
      - "8081:8080"  # Host 8081 mapped to Adminer 8080
    networks:
      - interview-net

networks:
  interview-net:
    driver: bridge

volumes:
  db_data:
